#!/usr/bin/env python

from ising import ising
import numpy as np
import matplotlib.pyplot as plt
random_wiring=False
sizes=2**np.arange(2,7)
R=10
mode='MonteCarlo'

Nbetas=101
betas=10**np.linspace(-1,1,Nbetas)
C=np.zeros((Nbetas,len(sizes),R))
for rep in range(R):
	plt.figure()
	for s,size in enumerate(sizes):
	
		
		filename='files/mode_'+mode+'-size_'+str(size)+'-ind_'+str(rep)+'.npz'
		data=np.load(filename)
		I=ising(size)
		I.h=data['h']
		I.J=data['J']
				
		for bind in range(Nbetas):
			Em=0
			E2m=0
			T=100000
			I.Beta=betas[bind]
			I.randomize_state()
			for t in range(int(T/10)):
				I.SequentialGlauberStep()
			for t in range(T):
				I.SequentialGlauberStep()
				E=-(np.dot(I.s,I.h) + np.dot(np.dot(I.s,I.J),I.s))
				Em+=E/T
				E2m+=E**2/T
			C[bind,s,rep]=I.Beta**2*(E2m-Em**2)/size
		
		plt.semilogx(betas,C[:,s,rep])
				
		print(mode,rep,size,np.max(C[:,s,rep]))
filename='heat-capacities.npz'
np.savez(filename, betas=betas,sizes=sizes,R=R,C=C)


plt.show()
